sudo: required
language: node_js
node_js:
- '8'
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.18.0
  global:
    secure: LGlbJsIc7n5hY6cHbVqpnq73jzJgB6QJ3gEsx3cVtQirkt1Qpj/IOcHGmsMavEkGg7+oOViFsZ7euhgyHPtg9lhkILudWcs3sFbVYHVS/jL3IUZGcM5+ip/Ss5uV7tc9cVLmRvf3C7UbvX8eyt+yQ0PSx8EGo44b1i/r3qpf/S1UX20xox0FMgA0924pR8DV+jtfzwvI1V/XJm9dXrl0Dm9O/7dzdfNQUwMcrSvj8d0DNhkKx4NTjqOSyz66phko7ql0rTCXOhNZ2La50KVg3CEsnf7sMLgvyFYVUAUWVxrAfWjOSDFnhna76zOQXt6X4ht6t0KtF3AqO92z4EaP3M1w62ZOfNgW/yDj2USO4tl+GKGzOaF9cT1yEbPODLrFfP4r8JTM5Fu/BBEFiOkDYUpngj+BBnizKAf/jXerEJdDEZNLMuIbFBgy4DfLvzi0A/mZPHna71YKxL55YjEHi+1f0Qg592EUmxc9uj13i7yvbgFarELW7PbaD1UWAmF1os+9/ftjI5x3IO/PufrsGl4KHlU2s4zpuaJOM5vKO0wjRjklh+/s6ZNwxbsJN4ffK3TCldddvYioVP1Un9smSswx3PPJTW0NmQTaOoESkbVd6Rb/QIQ6KzGcAW3IjgW35Sil4rdIf0BO6EWCe5bZTAlDQK98iFZW0dN15XB55Ro=
services:
  - docker
before_install:
  - cd ui-src
  - yarn install
  - yarn build
  - cd ..
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - TARGETDIR=$(pwd) docker-compose up -d
script:
  - docker run --rm -v "$(pwd):/litter" holochain/holochain-proto:develop bash -c "cd /litter; hcdev -no-nat-upnp -mdns=true test"
  - docker run --rm -v "$(pwd):/litter" holochain/holochain-proto:develop bash -c "cd /litter; hcdev -no-nat-upnp -mdns=true scenario collisionOfHandles"
  - docker run --rm -v "$(pwd):/litter" holochain/holochain-proto:develop bash -c "cd /litter; hcdev -no-nat-upnp -mdns=true scenario followAndShare"
  - cd ui-automation
  - npm install
  - npm test
  - cd ..
  - cd ui-src
  - npm run release:files
  - PACKAGE_NAME=$(node -p -e "require('./package.json').name")
  - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
  - cd ..
  - cd release
  - ls
  - zip -r $PACKAGE_NAME-$PACKAGE_VERSION.zip .
  - pwd
  - docker-compose kill
  - docker-compose down
cache:
  directories:
  - ui-automation/node_modules
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: $PACKAGE_NAME-$PACKAGE_VERSION.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master
